openapi: 3.0.4
info:
  title: Bible
  description: >-
    Bible is a simple tool for getting bible verses. Simply provide the book,
    chapter, and verse, and the API will return the verse.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/bible:
    get:
      summary: Get Bible Verse
      description: Get a bible chapter or verse based on the book, chapter, and or verse
      operationId: bible
      parameters:
        - name: book
          in: query
          schema:
            type: string
          required: true
          description: The name of the book in the bible (e.g., Genesis)
          example: Genesis
        - name: chapter
          in: query
          schema:
            type: integer
          required: true
          description: The chapter number in the book
          example: 5
        - name: verse
          in: query
          schema:
            type: integer
          required: false
          description: The verse number in the chapter
          example: 17
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  text: >-
                    But with thee will I establish my covenant; and thou shalt
                    come into the ark, thou, and thy sons, and thy wife, and thy
                    sons' wives with thee.
                  book: Genesis
                  abbr: gn
                  chapter: 5
                  verses:
                    - 17
                  version: KJV
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
