name: apiverve_bible
description: Bible is a simple tool for getting bible verses. Simply provide the book, chapter, and verse, and the API will return the verse.
version: 1.1.14
homepage: https://apiverve.com/marketplace/bible?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/bible-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
